### ISSUE TITLE
Ebi access the F/U data on FM Pro

### ISSUE THREAD

**Issue by mbcann01** [brad-cannell/detect_fu_interviews_public#11]
# Overview

Step one is to be able to access the F/U interview data that lives on FM Pro. There is already an Rmd file named `data_01_import.Rmd` that Brad can use to access the data directly from FM Pro. We need to make sure Ebi can use it too.

# Tasks

- [x] Get FM Pro login credentials.
- [x] Download and install the Filemaker ODBC driver on your computer.
- [x] Set up your login information in Keyring.
- [x] Make sure you can access the data.

**Comment by edambo** [comment]
@mbcann01 

- [x ] Get FM Pro login credentials.
- [x] Download and install the Filemaker ODBC driver on your computer.
- [x ] Set up your login information in Keyring.
- [x] Make sure you can access the data.

I was able to access the data using the ODBC package, but I had to make some changes to the code on my end: I couldn't run the code without including my username as an argument under key_get().

It also took a really long time (over 10 minutes before it stopped running and I could view the data frames. I'm not sure if this is normal or not. My VPN connection also wasn't very stable.

**Comment by mbcann01** [comment]
Hi Ebie!

Great job! We can troubleshoot the connection sometime and see if we can speed things up.

We will also need to work on the key ring code. We definitely can't keep your username in the code file. We'll get it figured out.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
