### ISSUE TITLE
Clean each data table individually

### ISSUE THREAD

**Issue by mbcann01** [brad-cannell/detect_fu_interviews_public#12]
# Overview

A lot of work has already been put into importing, checking, and wrangling each of the F/U interview data tables in FM Pro. However, it seems like the data management for some data tables is broken up into multiple code files. For example, one file for "qaqc" and a separate file for converting categorical vectors to factors. There may be a good reason for this, but if not, we should condense the files so that there is a single data cleaning code file for each data table. 

## Update 2023-06-12

Now that we are done collecting data, connecting directly to FileMaker Pro with ODBC is more time-consuming and complicated than necessary. I'd like us to start working with files directly in our local repository (not synced with GitHub). I'm adding some tasks below to help with that process.

# Tasks

- [x] Create a new Qmd file for importing and cleaning each data table in FM Pro. 
  * These will replace the existing Rmd files.
  * The code in the Rmd files should mostly be good. It just needs to be condensed. 
  * Name each file `data_01_<dataset name>_import.qmd`
    * For example, `data_01_aps_investigations_import.qmd`
  * Each cleaned data frame should be exported to the data folder in Rds format, and should be named `<dataset_name>_import.rds`. 
    * For example, `aps_investigations_import.rds`
    * **Please make sure to .gitignore each data frame.**
- [x] Create a new folder called 'data' in your local repository (if it doesn't already exist)
- [x] Add `data/` to your .gitignore file.
- [x] Create a new folder inside of `data` called `filemaker_pro_exports`.
- [x] Download all of the data tables from FM Pro as csv files and save them to [this shared folder on OneDrive](https://uthtmc-my.sharepoint.com/:f:/r/personal/michael_b_cannell_uth_tmc_edu/Documents/02%20Research/04%20DETECT/DETECT%20NIA%20R01/02%20Shared%20Folders/DETECT%20Follow-up%20Inereview%20Data%20Shared/detect_public/data/raw?csf=1&web=1&e=iNgLat).
- [x] Copy those files into `data/filemaker_pro_exports`
- [x] Update the import data code chunks in all of the data import Rmd files to import the data from `data/filemaker_pro_exports` instead of connecting directly to FM Pro using the ODBC connection. So, on both of our computers, the code to import the data should look something like, `read_csv("../data/filemaker_pro_exports/data_set_name.csv")`.
- [x] Update the [Wiki](https://github.com/brad-cannell/detect_fu_interviews_public/wiki) to reflect the new file structure.

**Comment by mbcann01** [comment]
Hi @edambo, I just uploaded a little more data to FM Pro today. I think that was the last bit of data that we will need to upload though.
