### ISSUE TITLE
Create a master descriptive tables website

### ISSUE THREAD

**Issue by mbcann01** [brad-cannell/detect_fu_interviews_public#32]
# Overview

We want to create a master table 1 as a Quarto website/book. It may look similar to the [master table we are creating for the Link2Care project](https://github.com/brad-cannell/link2care_master_table).

# Tasks

- [x] Create a repo for the website (Brad)
- [x] Create an "about" section of the website (Ebie)
- [x] Fill in some initial stats about recruitment and follow-up @edambo 
- [x] Add a single section of the follow-up interview to the website. Probably start with sociodemographics.
  - [x] Create a table of descriptive stats overall.
  - [x] Create a table of descriptive stats by EM status.

**Comment by mbcann01** [comment]
Hi @edambo 

Quick recap of our meeting today:
* How many follow-up interviews? If they gave consent, then they count. 
* How many unique people gave consent?
* How many interviews did people complete? Let's try putting this in table form. Give the N and percentage of people who completed 1 FU interview, 2 interviews, 3 interviews, etc.
