### ISSUE TITLE
Review the code used to create the analysis data

### ISSUE THREAD

**Issue by mbcann01** [brad-cannell/detect_fu_interviews_public#33]
# Overview

Several GRAs have worked hard to create an analysis data frame from the separate files exported by FileMaker Pro. I need to go review them all for correctness and stylistic consistency. Additionally, I need to create some instructions for using/updating files in the future. 

# Left off at

2023-12-04
- Was working on data_03_general_health_import.qmd. At line 548, there is a code block that drops "variables that have recoded forms" by number. I'm going to ask Ebie to drop them by name instead. I'm also going to ask her to update all of the across() code to select columns by name. 

# Tasks

- [ ] Review all of the data import and cleaning files
- [ ] Update the [Wiki](https://github.com/brad-cannell/detect_fu_interviews_public/wiki/Using-this-repository)

**Comment by mbcann01** [comment]
@edambo I think you will take a first pass at this, correct?

**Comment by edambo** [comment]
I'm not sure I understand @mbcann01. Are you asking if I worked on these already?

**Comment by mbcann01** [comment]
Hi @edambo ! I haven't checked yet. We just talked about it on Monday, so I didn't assume that you'd already done it. If so great!

**Comment by edambo** [comment]
@mbcann01 Ah, yes. I think I did this already if you mean deleting the files.

**Comment by mbcann01** [comment]
@edambo What about the other tasks listed above? Did you happen to do either of them?

**Comment by edambo** [comment]
@mbcann01 Yes, I think they were done before the holidays. I changed the style as you requested, but it's possible I missed something. Let me know if this is the case.

**Comment by mbcann01** [comment]
@edambo , I started looking through the code. In `data_01_aps_investigations_import.qmd` line 26, the code to import the data looks like this:

````
aps_inv <- read_csv("../data/filemaker_pro_exports/aps_investigations_import.csv")
````

However, that produces and error on my computer because that is not the file path to the data. Of course, I can just change the file path in the code to match the file path on my computer, but I want it to run on your computer too. What is the path to this file in your computer?

**Comment by edambo** [comment]
That is very odd because this path works on my system. I'm not sure why
it's not working. I just ran it and there were no errors.


Ebie

**Comment by edambo** [comment]
I haven't changed that specifically, but I've made other changes to the
data management files. I was waiting to finish working on the codebook
files to pull everything together but I will go ahead and send a pull
request now.

**Comment by mbcann01** [comment]
2024-03-15

Left off at:
- Review all of the data import and cleaning files.
- `data_01`.

**Comment by mbcann01** [comment]
2024-03-21

Left off at:
- Review all of the data import and cleaning files.
- Finished `data_02`.
- Going through `check_consenting_participants.qmd` to see if that needs to be a separate file or if it can be combined with `data_02`. Left off on line 22 -- creating a more efficient way to read in the files.

Copy and paste for commits:

````
Brad's review of check_consenting_participants.qmd
Part of #33 
- Use the `here` package to facilitate file import and export.
- Made headings more consistent.
- Checked for overlap with qaqc/check_consenting_participants.qmd. There was nothing in the QAQC file that wasn't also in the data import file. Deleted the QAQC file.
- Added two carriage returns before level one headings.
````

**Comment by mbcann01** [comment]
2024-03-22

Left off at:
- Review all of the data import and cleaning files.
- Finished `data_02`.
- Going through `check_consenting_participants.qmd` to see if that needs to be a separate file or if it can be combined with `data_02`. Left off on line 115 -- trying to recreate Ebie's results.

Copy and paste for commits:

````
Brad's review of check_consenting_participants.qmd
Part of #33 
- Use the `here` package to facilitate file import and export.
- Made headings more consistent.
- Checked for overlap with qaqc/check_consenting_participants.qmd. There was nothing in the QAQC file that wasn't also in the data import file. Deleted the QAQC file.
- Added two carriage returns before level one headings.
- Simplified some of the code.
````

**Comment by mbcann01** [comment]
2024-04-04

Left off at:
- Review all of the data import and cleaning files.
- Finished `data_02`.
- Going through `check_consenting_participants.qmd` to see if that needs to be a separate file or if it can be combined with `data_02`. Left off on line 118 -- trying to recreate Ebie's results.

Copy and paste for commits:

````
Brad's review of check_consenting_participants.qmd
Part of #33 
- Use the `here` package to facilitate file import and export.
- Made headings more consistent.
- Checked for overlap with qaqc/check_consenting_participants.qmd. There was nothing in the QAQC file that wasn't also in the data import file. Deleted the QAQC file.
- Added two carriage returns before level one headings.
- Simplified some of the code.
````

**Comment by mbcann01** [comment]
2024-04-05

Reviewing `data_06_self_report_import.qmd`

- Yesterday, I went down a rabbit hole trying to write a function to recode, factor, and relocate columns. But, even if I'm successful, it probably won't buy me a lot. So, I moved that code over to `exploratory/recoding_factoring_relocating.qmd`, and I'm abandoning it for now.
- For now, work through the items below:
  - [ ] There is a lot of tidyselect code being used to select columns inside of across() for recoding factors. Let's use explicit column names instead so that the code is easier to reason about. 
  - [ ] Change coding for all "Yes/No" columns from "1/2" to "1/0".
  - [ ] Spot check the factor code.

When you are done reviewing `data_06_self_report_import.qmd`, go back to reviewing `check_consenting_participants.qmd`.

**Comment by mbcann01** [comment]
2024-04-05

Reviewing `data_06_self_report_import.qmd`

- Left off on line **163**
- Base this file off of `qaqc/data_01_self_report_recode_facotors.Rmd`. That file recoded columns more accurately in some cases.
- I created some helper functions that recode, factor, and relocate. Use them to: 
  - There is a lot of tidyselect code being used to select columns inside of across() for recoding factors. Let's use explicit column names instead so that the code is easier to reason about. 
  - Change coding for all "Yes/No" columns from "1/2" to "1/0".
  - Check to make sure the "Don't know" values are being recoded correctly.
  - Spot check the factor code. `data_01_self_report_recode_factor.Rmd` seems more accurate so far.

When you are done reviewing `data_06_self_report_import.qmd`, change coding for all "Yes/No" columns from "1/2" to "1/0" in `data_01` and `data_02`.

Then, go back to reviewing `check_consenting_participants.qmd`.

**Comment by mbcann01** [comment]
2024-04-10

Reviewing `data_06_self_report_import.qmd`

- Left off on line **807**
- Base this file off of `qaqc/data_01_self_report_recode_facotors.Rmd`. That file recoded columns more accurately in some cases.

When you are done reviewing `data_06_self_report_import.qmd`, change coding for all "Yes/No" columns from "1/2" to "1/0" in `data_01` and `data_02`.

Then, go back to reviewing `check_consenting_participants.qmd`.
- Use the double colon method instead of loading the readr package.

**Comment by mbcann01** [comment]
2024-04-11

- Finished reviewing `data_06_self_report_import.qmd`, `data_01_aps_investigations_import.qmd`, and `data_02_consent_import.qmd`
- Go back to reviewing `check_consenting_participants.qmd`
  - Use the double colon method instead of loading the readr package.

**Comment by mbcann01** [comment]
2024-04-16

- Finished reviewing `check_consenting_participants.qmd`.
- Make a note at the top that the IDs below won't show up anymore because we fixed them.

**Comment by mbcann01** [comment]
2024-04-26

-  Review `data_03_clutter_scale_import.qmd`
